version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/WordPress/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/setup_env.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
